# Generated by Django 4.0.2 on 2022-02-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confPassw',
        ),
    ]
